feat: add day02 haha solution
Rabbittee/JavaScript30 pull request #10
Opened 2022-01-04 08:58 UTC by haha861924

2022-01-05 14:56 UTC, kevinshu1995 requested changes
吠吠超強!
寫得好好懂~

1. day 2 的 README 內!
2. day 1 的檔案應該要排除啦!

2022-01-05 14:56 UTC, kevinshu1995 commented on day02/haha/utils.js
> +    sec: (360 / 60) * sec + 90,
我覺得那個 90 可以另外拉出來，有點 magic 的味道XD

2022-01-06 05:34 UTC, haha861924 commented on day02/haha/utils.js
> +    sec: (360 / 60) * sec + 90,
**凱文超強!**
重構了 謝謝凱文

2022-01-08 08:15 UTC, kevinshu1995 reviewed
readme 太讚惹

2022-01-08 08:22 UTC, kevinshu1995 approved these changes

2022-01-08 08:23 UTC, merged