Day02 done
Rabbittee/JavaScript30 pull request #38
Opened 2022-01-05 13:35 UTC by lee926427

2022-01-05 14:06 UTC, haha861924 commented on day02/recoil/README.md
> +  12     const hourDegree = 360 / 12; //計算每小時多少度
時針角度計算的方式沒這麼單純，還要考慮分針動的時候，時針的度數也會跟著增加
請參考 **[高年級資優數學](https://www.youtube.com/watch?v=_P9kLVRzYuA)**

ps: 因為我也踩到雷

2022-01-05 14:13 UTC, lee926427 commented on day02/recoil/README.md
> +  12     const hourDegree = 360 / 12; //計算每小時多少度
感謝吠吠，可惡的數數兒到處都埋陷阱

2022-01-05 15:21 UTC, kevinshu1995 requested changes
又是超詳細 readme!

1. 吠吠提到的時針，再麻煩修改一下
2. day 1 的檔案再麻煩拆去 day 1 的分支喔~

2022-01-05 15:42 UTC, lee926427 commented
確認一下我目前是照[這個流程發PR](https://rabbit-church.notion.site/JS30-git-2bc3ca3239444002acf5823a171da47d)的
所以rebase之後不能直接git checkout -b 切換分支，而是要先切回main再開新分支對吧?

2022-01-05 15:55 UTC, kevinshu1995 commented
> 確認一下我目前是照[這個流程發PR](https://rabbit-church.notion.site/JS30-git-2bc3ca3239444002acf5823a171da47d)的 所以rebase之後不能直接git checkout -b 切換分支，而是要先切回main再開新分支對吧?

對~ 沒有錯

2022-01-06 06:06 UTC, kevinshu1995 commented on day02/recoil/script.js
> +  hourElement.style = degree((now.getHours() * hourDegree)+(now.getMinutes() * hourDegree));
時針，根據分鐘數多給的角度錯啦! 這樣太多

2022-01-06 06:08 UTC, kevinshu1995 requested changes
時針要改一下~

另外看要不要嘗試 force push 把 day 1 的 commit 洗掉

2022-01-06 06:34 UTC, closed without merging