feat: 🎸  day 2 alpha's solution
Rabbittee/JavaScript30 pull request #41
Opened 2022-01-05 14:17 UTC by alphatero

數學不會就是不會

2022-01-05 14:18 UTC, haha861924 commented
> 數學不會就是不會

agree.

2022-01-05 14:35 UTC, haha861924 commented on day02/alpha/main.js
> +  rotate(hourHand.element, caculateDeg(hourHand.value * 2, 24));
老師我有問題!
24 行取得當日的小時，是 24 小時制的，這樣接下來的計算方式不會爆掉嗎 
或是我數學不好 <br>
![image](https://user-images.githubusercontent.com/40877568/148234923-ba5e9b27-697c-4c90-a321-7ff0dc96ad13.png)

2022-01-05 14:38 UTC, alphatero commented on day02/alpha/main.js
> +  rotate(hourHand.element, caculateDeg(hourHand.value * 2, 24));
老師 乾我這邊寫錯位置惹就跟你說數學不會就不會！

2022-01-05 15:54 UTC, kevinshu1995 requested changes
又是個超詳細 readme!

1. 要記得把 day 1 的部分從這個分支拿掉喔!
2. env 的路徑設定錯誤惹
3. 計算指針角度那邊可能要麻煩說明一下XD

2022-01-05 15:54 UTC, kevinshu1995 commented on day02/alpha/.env
> +VITE_APP_GITHUB=https://github.com/Rabbittee/JavaScript30/tree/main/day02/alpha
前面的路徑應該錯惹，應該是這樣

https://rabbittee.github.io/JavaScript30/

2022-01-05 15:54 UTC, kevinshu1995 commented on day02/alpha/main.js
> +};
甚麼~ 我不懂 XD 
感覺怪怪的，應該不對?

不過還是要記得時針的計算還要包含分鐘進去，不然 12:59 這種看起來就會怪怪的

2022-01-06 00:32 UTC, alphatero commented on day02/alpha/.env
> +VITE_APP_GITHUB=https://github.com/Rabbittee/JavaScript30/tree/main/day02/alpha
凱文超強

2022-01-06 00:33 UTC, alphatero commented on day02/alpha/main.js
> +};
求教！我不會數數兒！

2022-01-06 00:35 UTC, alphatero commented on day02/alpha/main.js
> +};
https://zh.wikipedia.org/wiki/%E6%97%B6%E9%92%9F%E9%97%AE%E9%A2%98
我找了藉個哈哈哈哈

2022-01-06 04:31 UTC, alphatero commented
@kevinshu1995  凱文救我～

2022-01-06 05:27 UTC, kevinshu1995 commented
484 忘記重新 build 惹

2022-01-06 05:29 UTC, alphatero commented
> 484 忘記重新 build 惹

火眼金睛凱文！！！！！

2022-01-06 05:47 UTC, kevinshu1995 commented on day02/alpha/main.js
> +};
不行 我不能理解 為甚麼要乘上 360 XDDD
不過看起來結果是對的，那就一定是大拇指的啦

2022-01-06 05:49 UTC, kevinshu1995 approved these changes

2022-01-06 05:50 UTC, merged

2022-01-06 06:09 UTC, alphatero commented on day02/alpha/main.js
> +};
因為一圈360度啊0.0 你先算好譬如 11:59:08是多少小時 就是
`11 + 59/60 + 8/3600`
多少分`59 + 8 / 60`
多少秒 `8`
加起來然後除以12 因為一圈有12小時 不用理會超過24小時因為過了360就是另一圈
這樣

2022-01-06 15:38 UTC, kevinshu1995 commented on day02/alpha/main.js
> +};
阿 我懂了
因為我的邏輯是反過來的，原來可以這樣算