Feat/day02 kim
Rabbittee/JavaScript30 pull request #63
Opened 2022-01-07 07:29 UTC by kayac-chang

2022-01-07 13:19 UTC, kayac-chang reviewed
Please take a loop @KimberlyYen

2022-01-07 13:19 UTC, kayac-chang commented on day02/kim/index.js
> +    console.log(element);
please remove `console.log` on source code.

2022-01-08 08:45 UTC, kevinshu1995 requested changes
@KimberlyYen 
看起來都讚讚的。
1. html 呢 XDD
2. console 請拿掉~
3. 可以玩玩看 markdown 語法

2022-01-08 08:45 UTC, kevinshu1995 commented on day02/kim/README.md
> +JS 套時鐘的角度公式
要嘗試看看 markdown 語法嗎~
例如: 清單的語法
- 像這樣子
> 或是這樣註解

--- 

[markdown 語法參考連結](https://wcc723.github.io/development/2019/11/23/ten-mins-learn-markdown/)

2022-01-08 08:45 UTC, kevinshu1995 commented on day02/kim/index.js
> +  // 呼叫樣式
如哈囉所說，這邊其實不是呼叫樣式
可以叫做 "宣告 DOM 元素"

2022-01-08 12:51 UTC, KimberlyYen commented
> Please take a loop @KimberlyYen

loop ?

2022-01-08 12:53 UTC, KimberlyYen commented
> 看起來都讚讚的。

謝謝！🥲 你的鼓勵是我前進的動力！
~我在選里長膩~

2022-01-09 07:35 UTC, kevinshu1995 approved these changes
給你一個讚

2022-01-09 07:35 UTC, merged